# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d9e1f2f94be8af5138d8a52e97c9c28fd227c8660098dc277ef6f1050e35ff9caac311c9e1f2d9e3ab41fcdf78c68516994f5176fdab210ae8e9e56008edaf

test:
  secret_key_base: a292f8e2504c41c02540472ebc0bd0416d1040820290e499f466c55407a433548e6c051e3d539a269cf7b0e99eb2454843c6ca59026b8848be2de6b6d246f280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
